// NOWPayments Mass Payouts — VERIFY step.
//
// Companion to nowpayments-payout. A human admin/gosat operator reads the 2FA
// code (sent by NOWPayments to the account email or generated by an
// authenticator app) and submits it through the admin UI. This function:
//   1. Authenticates the caller as admin or gosat via JWT + user_roles.
//   2. Re-authenticates with NOWPayments (/v1/auth) to obtain a fresh JWT.
//   3. Calls POST /v1/payout/{batch_id}/verify with the code.
//   4. On success, marks the bestowal payout_status='sent' and stamps
//      payout_completed_at.
//   5. On failure, returns the provider error verbatim so the operator can
//      retry — NOWPayments allows multiple attempts on the same batch.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import { corsHeaders } from "npm:@supabase/supabase-js@2/cors";

const NOWPAYMENTS_API = "https://api.nowpayments.io/v1";

interface VerifyRequest {
  bestowalId: string;
  code: string;
}

async function getNowPaymentsJwt(email: string, password: string): Promise<string> {
  const res = await fetch(`${NOWPAYMENTS_API}/auth`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email, password }),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`nowpayments_auth_http_${res.status}: ${text}`);
  const parsed = JSON.parse(text) as { token?: string };
  if (!parsed.token) throw new Error("nowpayments_auth_no_token");
  return parsed.token;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);

  const supabaseUrl = Deno.env.get("SUPABASE_URL");
  const anonKey = Deno.env.get("SUPABASE_ANON_KEY");
  const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  const apiKey = Deno.env.get("NOWPAYMENTS_API_KEY");
  const email = Deno.env.get("NOWPAYMENTS_EMAIL");
  const password = Deno.env.get("NOWPAYMENTS_PASSWORD");

  if (!supabaseUrl || !anonKey || !serviceRoleKey || !apiKey) {
    return json({ error: "server_misconfigured" }, 500);
  }
  if (!email || !password) {
    return json({ error: "nowpayments_credentials_missing" }, 500);
  }

  // 1. Caller auth + role check.
  const authHeader = req.headers.get("Authorization") ?? "";
  if (!authHeader.startsWith("Bearer ")) {
    return json({ error: "unauthorized" }, 401);
  }
  const userClient = createClient(supabaseUrl, anonKey, {
    global: { headers: { Authorization: authHeader } },
  });
  const token = authHeader.slice("Bearer ".length);
  const { data: claims, error: claimsErr } = await userClient.auth.getClaims(token);
  if (claimsErr || !claims?.claims?.sub) {
    return json({ error: "unauthorized" }, 401);
  }
  const userId = claims.claims.sub as string;

  const admin = createClient(supabaseUrl, serviceRoleKey, {
    auth: { persistSession: false },
  });

  const { data: roleRows, error: rolesErr } = await admin
    .from("user_roles")
    .select("role")
    .eq("user_id", userId);
  if (rolesErr) return json({ error: "role_lookup_failed" }, 500);
  const roles = (roleRows ?? []).map((r: { role: string }) => String(r.role).toLowerCase());
  if (!roles.includes("admin") && !roles.includes("gosat")) {
    return json({ error: "forbidden" }, 403);
  }

  // 2. Parse + validate body.
  let body: VerifyRequest;
  try {
    body = await req.json();
  } catch {
    return json({ error: "invalid_json" }, 400);
  }
  if (!body?.bestowalId || !body?.code) {
    return json({ error: "missing_fields" }, 400);
  }

  // 3. Look up the payout_reference (the NOWPayments batch id) for this bestowal.
  const { data: bestowal, error: bestowalErr } = await admin
    .from("bestowals")
    .select("id, payout_status, payout_reference")
    .eq("id", body.bestowalId)
    .maybeSingle();
  if (bestowalErr) return json({ error: bestowalErr.message }, 500);
  if (!bestowal) return json({ error: "bestowal_not_found" }, 404);
  if (!bestowal.payout_reference) {
    return json({ error: "no_payout_reference_on_bestowal" }, 400);
  }
  if (bestowal.payout_status !== "awaiting_2fa") {
    return json({
      error: "bestowal_not_awaiting_2fa",
      payout_status: bestowal.payout_status,
    }, 409);
  }

  // 4. Re-auth with NOWPayments and call verify.
  try {
    const jwt = await getNowPaymentsJwt(email, password);
    const res = await fetch(
      `${NOWPAYMENTS_API}/payout/${encodeURIComponent(bestowal.payout_reference)}/verify`,
      {
        method: "POST",
        headers: {
          "x-api-key": apiKey,
          "Authorization": `Bearer ${jwt}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ verification_code: body.code }),
      },
    );
    const text = await res.text();
    let parsed: Record<string, unknown> = {};
    try {
      parsed = text ? JSON.parse(text) : {};
    } catch { /* keep raw */ }

    if (!res.ok) {
      // Don't mutate the bestowal — let the operator retry with a fresh code.
      return json({
        error: `nowpayments_verify_http_${res.status}`,
        detail: parsed,
      }, 400);
    }

    // 5. Mark sent.
    const completedAt = new Date().toISOString();
    const { error: updateErr } = await admin
      .from("bestowals")
      .update({
        payout_status: "sent",
        payout_completed_at: completedAt,
        payout_error: null,
      })
      .eq("id", body.bestowalId);
    if (updateErr) {
      return json({
        error: "verified_but_bestowal_update_failed",
        detail: updateErr.message,
        raw: parsed,
      }, 500);
    }

    return json({
      ok: true,
      bestowalId: body.bestowalId,
      payoutReference: bestowal.payout_reference,
      payoutStatus: "sent",
      completedAt,
      raw: parsed,
    });
  } catch (err) {
    return json({ error: err instanceof Error ? err.message : String(err) }, 500);
  }
});

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}
