// Persistent <audio loop> elements for the incoming-call ringtone and the
// caller's ring-back tone -- replaces the earlier Web Audio synth
// (createToneLoop/startSimpleRingtone/startRingbackTone in ringtone.ts),
// which stayed silent on at least one real iPhone despite
// AudioUnlocker.tsx's shared AudioContext being primed. A real <audio>
// element primed with a real play()-then-pause() inside a genuine user
// gesture is the standard, better-supported autoplay-unlock path on iOS
// Safari -- see public/sounds/ (generated by scripts/generate-ringtones.mjs)
// for why these are .wav, not .mp3/.ogg.
//
// One element each, created once and reused (never re-created per call)
// so the "primed" state from the original gesture carries forward to
// every later play() call triggered by a realtime/poll event instead of
// a gesture.

let ringtoneEl: HTMLAudioElement | null = null;
let ringbackEl: HTMLAudioElement | null = null;
let primed = false;

function getRingtoneEl(): HTMLAudioElement {
  if (!ringtoneEl) {
    ringtoneEl = new Audio('/sounds/ringtone.wav');
    ringtoneEl.loop = true;
    ringtoneEl.preload = 'auto';
  }
  return ringtoneEl;
}

function getRingbackEl(): HTMLAudioElement {
  if (!ringbackEl) {
    ringbackEl = new Audio('/sounds/ringback.wav');
    ringbackEl.loop = true;
    ringbackEl.preload = 'auto';
  }
  return ringbackEl;
}

export function isCallAudioPrimed(): boolean {
  return primed;
}

/**
 * Call from inside a real user gesture (pointerdown/touchstart/click) --
 * play() then immediately pause() each element so iOS Safari's autoplay
 * policy treats a LATER play() call (triggered by a realtime event, not
 * a gesture) as already allowed. Only marks primed if both play() calls
 * actually resolved; safe to call again later if it didn't (e.g. from
 * the "Enable Sound" button at call time).
 */
export async function primeCallAudio(): Promise<boolean> {
  if (primed) return true;
  try {
    const rt = getRingtoneEl();
    const rb = getRingbackEl();
    await rt.play();
    rt.pause();
    rt.currentTime = 0;
    await rb.play();
    rb.pause();
    rb.currentTime = 0;
    primed = true;
    return true;
  } catch (e) {
    console.warn('[callAudio] priming failed (will retry on next gesture/button tap)', e);
    return false;
  }
}

/** Resolves true if playback actually started, false if the browser blocked it. */
export async function playRingtone(): Promise<boolean> {
  const el = getRingtoneEl();
  try {
    el.currentTime = 0;
    await el.play();
    return true;
  } catch (e) {
    console.warn('[callAudio] playRingtone blocked', e);
    return false;
  }
}

export function stopRingtone(): void {
  if (!ringtoneEl) return;
  try {
    ringtoneEl.pause();
    ringtoneEl.currentTime = 0;
  } catch { /* element may be in a bad state momentarily -- next play() call recovers */ }
}

/** Resolves true if playback actually started, false if the browser blocked it. */
export async function playRingback(): Promise<boolean> {
  const el = getRingbackEl();
  try {
    el.currentTime = 0;
    await el.play();
    return true;
  } catch (e) {
    console.warn('[callAudio] playRingback blocked', e);
    return false;
  }
}

export function stopRingback(): void {
  if (!ringbackEl) return;
  try {
    ringbackEl.pause();
    ringbackEl.currentTime = 0;
  } catch { /* element may be in a bad state momentarily -- next play() call recovers */ }
}
