var interfaceConfig = {
    TOOLBAR_BUTTONS: [
        'microphone', 'camera', 'closedcaptions', 'desktop', 'fullscreen',
        'fodeviceselection', 'hangup', 'profile', 'chat', 'recording',
        'livestreaming', 'etherpad', 'sharedvideo', 'settings', 'raisehand',
        'videoquality', 'filmstrip', 'invite', 'feedback', 'stats', 'shortcuts',
        'tileview', 'videobackgroundblur', 'download', 'help', 'mute-everyone',
        'security'
    ],
    MOBILE_APP_PROMO: false,
    SETTINGS_SECTIONS: ['devices', 'language', 'moderator', 'profile'],
    DEFAULT_BACKGROUND: '#474747',
    INITIAL_TOOLBAR_TIMEOUT: 20000,
    TOOLBAR_TIMEOUT: 4000,
    TOOLBAR_ALWAYS_VISIBLE: false,
    DEFAULT_REMOTE_DISPLAY_NAME: 'Fellow Jitster',
    DEFAULT_LOCAL_DISPLAY_NAME: 'me',
    SHOW_JITSI_WATERMARK: true,
    SHOW_WATERMARK_FOR_GUESTS: true,
    SHOW_BRAND_WATERMARK: false,
    BRAND_WATERMARK_LINK: '',
    SHOW_POWERED_BY: false,
    DISPLAY_WELCOME_PAGE_CONTENT: true,
    DISPLAY_WELCOME_PAGE_TOOLBAR_ADDITIONAL_CONTENT: false,
    APP_NAME: 'Jitsi Meet',
    NATIVE_APP_NAME: 'Jitsi Meet',
    PROVIDER_NAME: 'Jitsi',
    LANG_DETECTION: true,
    CONFIGURE_NOW: 'CONFIGURE NOW',
    BYPASS_JOIN_LEAVE_NOTIFICATIONS: false,
    CLOSE_PAGE_GUEST_HAS_LEFT: false,
    SHOW_PROMOTIONAL_CLOSE_PAGE: false,
    ENABLE_DIAL_OUT: false,
    ENABLE_FEEDBACK_ANIMATION: false,
    DISABLE_FOCUS_INDICATOR: false,
    DISABLE_DOMINANT_SPEAKER_INDICATOR: false,
    DISABLE_JOIN_LEAVE_NOTIFICATIONS: false,
    DISABLE_PRESENCE_STATUS: false,
    DISABLE_RINGING: false,
    AUDIO_LEVEL_PRIMARY_COLOR: 'rgba(255,255,255,0.4)',
    AUDIO_LEVEL_SECONDARY_COLOR: 'rgba(255,255,255,0.2)',
    POLICY_LOGO: null,
    PROVIDER_NAME: 'Jitsi',
    DEFAULT_LANGUAGE: 'en',
    AUTO_PIN_LATEST_SCREEN_SHARE: 'remote-only',
    ENABLE_FILE_UPLOAD: false,
    FILENAME_READONLY: true,
    ENABLE_WELCOME_PAGE: true,
    ENABLE_CLOSE_PAGE: false,
    ENABLE_PREJOIN_PAGE: true,
    ENABLE_WELCOME_PAGE_TOOLBAR_BUTTON: true,
    PREJOIN_PAGE_ENABLED: true,
    CLOSE_PAGE_GUEST_HAS_LEFT: false,
    SHOW_PROMOTIONAL_CLOSE_PAGE: false,
    SHOW_BRAND_WATERMARK: false,
    BRAND_WATERMARK_LINK: '',
    SHOW_POWERED_BY: false,
    SHOW_JITSI_WATERMARK: true,
    SHOW_WATERMARK_FOR_GUESTS: true,
    DISPLAY_WELCOME_PAGE_CONTENT: true,
    DISPLAY_WELCOME_PAGE_TOOLBAR_ADDITIONAL_CONTENT: false,
    APP_NAME: 'Jitsi Meet',
    NATIVE_APP_NAME: 'Jitsi Meet',
    PROVIDER_NAME: 'Jitsi',
    LANG_DETECTION: true,
    CONFIGURE_NOW: 'CONFIGURE NOW',
    BYPASS_JOIN_LEAVE_NOTIFICATIONS: false,
    ENABLE_DIAL_OUT: false,
    ENABLE_FEEDBACK_ANIMATION: false,
    DISABLE_FOCUS_INDICATOR: false,
    DISABLE_DOMINANT_SPEAKER_INDICATOR: false,
    DISABLE_JOIN_LEAVE_NOTIFICATIONS: false,
    DISABLE_PRESENCE_STATUS: false,
    DISABLE_RINGING: false,
    AUDIO_LEVEL_PRIMARY_COLOR: 'rgba(255,255,255,0.4)',
    AUDIO_LEVEL_SECONDARY_COLOR: 'rgba(255,255,255,0.2)',
    POLICY_LOGO: null,
    PROVIDER_NAME: 'Jitsi',
    DEFAULT_LANGUAGE: 'en',
    AUTO_PIN_LATEST_SCREEN_SHARE: 'remote-only',
    ENABLE_FILE_UPLOAD: false,
    FILENAME_READONLY: true,
    ENABLE_WELCOME_PAGE: true,
    ENABLE_CLOSE_PAGE: false,
    ENABLE_PREJOIN_PAGE: true,
    ENABLE_WELCOME_PAGE_TOOLBAR_BUTTON: true,
    PREJOIN_PAGE_ENABLED: true
};

