-- Creates 20 Wandering Hearts (Tribal Hearts) seed profiles for browse
-- testing: 10 men seeking women (seed-wh-01..10), 10 women seeking men
-- (seed-wh-11..20). Emails seed-wh-01@sow2grow.test .. seed-wh-20@sow2grow.test.
--
-- Generated by this session -- NOT executed automatically. Creating 20 real
-- auth.users rows in one shot was blocked by the sandbox's safety
-- classifier (a bulk write to the auth system is exactly the kind of
-- consequential action that should get a human's eyes first), so this is
-- handed off as a script instead of applied directly.
--
-- What each block does, per person:
--   1. INSERT INTO auth.users -- a real account. Password is a bcrypt hash
--      of a random UUID that is generated and discarded in the same
--      expression (crypt(gen_random_uuid()::text, gen_salt('bf'))) --
--      nobody, including this script, ever knows the plaintext, so the
--      account is genuinely unusable to log into. Requires pgcrypto
--      (already enabled on this project).
--   2. INSERT INTO auth.identities -- the matching email/password identity
--      GoTrue expects alongside the auth.users row.
--   3. UPDATE public.profiles -- the project's own `handle_new_user()`
--      trigger on auth.users fires automatically and creates the base
--      profiles row (first_name/country/location from raw_user_meta_data);
--      this just adds a realistic display_name on top.
--   4. INSERT INTO public.tribal_hearts_profiles -- the actual dating
--      profile: gender, seeking, birthdate (age 25-55), bio, 3-5 interests
--      (from the same INTERESTS list TribalHeartsOnboarding.tsx uses),
--      South African + international cities, is_seed = true.
--   5. INSERT INTO public.s2g_agent_free_access -- grants
--      is_tribal_hearts_member() membership (same table used to grant it
--      to davison -- see spec-payments.md/session notes for why this
--      table rather than fabricating fake ambassador_applications rows:
--      that table represents a real business process, this one is exactly
--      "internal/test access").
--
-- Run in the Supabase SQL editor (Studio) or via the Management API.
-- To undo: scripts/purge-wh-seed.sql.

BEGIN;

INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '4101e0f6-2d04-43ce-a7b2-ad800d149086', 'authenticated', 'authenticated',
  'seed-wh-01@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Thabo', 'country', 'South Africa', 'location', 'Cape Town'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), '4101e0f6-2d04-43ce-a7b2-ad800d149086', '4101e0f6-2d04-43ce-a7b2-ad800d149086',
  jsonb_build_object('sub', '4101e0f6-2d04-43ce-a7b2-ad800d149086', 'email', 'seed-wh-01@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Thabo Nkosi' WHERE user_id = '4101e0f6-2d04-43ce-a7b2-ad800d149086';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  '4101e0f6-2d04-43ce-a7b2-ad800d149086', 'Thabo', 'male', 'female', '1997-06-15',
  'Software developer who spends weekends braaiing with friends and hiking Table Mountain. Looking for someone to share good coffee and deep conversations with.', ARRAY['Hiking','Coffee','Deep talks','Music','Adventure']::text[], 'South Africa', 'Cape Town',
  ARRAY['/wandering-hearts/avatar-male.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('4101e0f6-2d04-43ce-a7b2-ad800d149086', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', 'fe8cd65d-ebf7-453b-9a13-f07ad8571137', 'authenticated', 'authenticated',
  'seed-wh-02@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Liam', 'country', 'United Kingdom', 'location', 'London'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), 'fe8cd65d-ebf7-453b-9a13-f07ad8571137', 'fe8cd65d-ebf7-453b-9a13-f07ad8571137',
  jsonb_build_object('sub', 'fe8cd65d-ebf7-453b-9a13-f07ad8571137', 'email', 'seed-wh-02@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Liam O''Connor' WHERE user_id = 'fe8cd65d-ebf7-453b-9a13-f07ad8571137';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  'fe8cd65d-ebf7-453b-9a13-f07ad8571137', 'Liam', 'male', 'female', '1992-06-15',
  'Architect with a soft spot for old churches and new cities. I believe in slow mornings and genuine connection.', ARRAY['Travel','Art','Books','Quiet evenings','Faith']::text[], 'United Kingdom', 'London',
  ARRAY['/wandering-hearts/avatar-male.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('fe8cd65d-ebf7-453b-9a13-f07ad8571137', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '7e05a471-ca16-410c-abdf-fd5ff3a901b9', 'authenticated', 'authenticated',
  'seed-wh-03@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Sipho', 'country', 'South Africa', 'location', 'Johannesburg'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), '7e05a471-ca16-410c-abdf-fd5ff3a901b9', '7e05a471-ca16-410c-abdf-fd5ff3a901b9',
  jsonb_build_object('sub', '7e05a471-ca16-410c-abdf-fd5ff3a901b9', 'email', 'seed-wh-03@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Sipho Dlamini' WHERE user_id = '7e05a471-ca16-410c-abdf-fd5ff3a901b9';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  '7e05a471-ca16-410c-abdf-fd5ff3a901b9', 'Sipho', 'male', 'female', '1985-06-15',
  'Father of two, small business owner, and a firm believer that family comes first. Enjoy Sunday lunches and long drives.', ARRAY['Family','Farming','Faith','Cooking','Nature']::text[], 'South Africa', 'Johannesburg',
  ARRAY['/wandering-hearts/avatar-male.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('7e05a471-ca16-410c-abdf-fd5ff3a901b9', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', 'b493a47e-8526-46f6-a752-caa74ec5e6d0', 'authenticated', 'authenticated',
  'seed-wh-04@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Daniel', 'country', 'Kenya', 'location', 'Nairobi'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), 'b493a47e-8526-46f6-a752-caa74ec5e6d0', 'b493a47e-8526-46f6-a752-caa74ec5e6d0',
  jsonb_build_object('sub', 'b493a47e-8526-46f6-a752-caa74ec5e6d0', 'email', 'seed-wh-04@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Daniel Osei' WHERE user_id = 'b493a47e-8526-46f6-a752-caa74ec5e6d0';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  'b493a47e-8526-46f6-a752-caa74ec5e6d0', 'Daniel', 'male', 'female', '1999-06-15',
  'Fitness coach and amateur chef. I take my coffee seriously and my workouts more seriously.', ARRAY['Fitness','Cooking','Coffee','Adventure','Music']::text[], 'Kenya', 'Nairobi',
  ARRAY['/wandering-hearts/avatar-male.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('b493a47e-8526-46f6-a752-caa74ec5e6d0', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '45716db9-b86f-4e29-9866-006a226c23bc', 'authenticated', 'authenticated',
  'seed-wh-05@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'James', 'country', 'South Africa', 'location', 'Durban'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), '45716db9-b86f-4e29-9866-006a226c23bc', '45716db9-b86f-4e29-9866-006a226c23bc',
  jsonb_build_object('sub', '45716db9-b86f-4e29-9866-006a226c23bc', 'email', 'seed-wh-05@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'James Whitfield' WHERE user_id = '45716db9-b86f-4e29-9866-006a226c23bc';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  '45716db9-b86f-4e29-9866-006a226c23bc', 'James', 'male', 'female', '1974-06-15',
  'Retired naval officer, now runs a small sailing school. Looking for a companion for life''s second chapter.', ARRAY['Nature','Travel','Quiet evenings','Books','Faith']::text[], 'South Africa', 'Durban',
  ARRAY['/wandering-hearts/avatar-male.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('45716db9-b86f-4e29-9866-006a226c23bc', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', 'f233f4c6-b078-4694-ac9b-195f43a9a5f5', 'authenticated', 'authenticated',
  'seed-wh-06@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Kabelo', 'country', 'South Africa', 'location', 'Pretoria'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), 'f233f4c6-b078-4694-ac9b-195f43a9a5f5', 'f233f4c6-b078-4694-ac9b-195f43a9a5f5',
  jsonb_build_object('sub', 'f233f4c6-b078-4694-ac9b-195f43a9a5f5', 'email', 'seed-wh-06@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Kabelo Molefe' WHERE user_id = 'f233f4c6-b078-4694-ac9b-195f43a9a5f5';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  'f233f4c6-b078-4694-ac9b-195f43a9a5f5', 'Kabelo', 'male', 'female', '1995-06-15',
  'Civil engineer by day, guitarist by night. I love a good braai and an even better playlist.', ARRAY['Music','Dancing','Farming','Deep talks','Adventure']::text[], 'South Africa', 'Pretoria',
  ARRAY['/wandering-hearts/avatar-male.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('f233f4c6-b078-4694-ac9b-195f43a9a5f5', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '99a216de-4979-48a1-b31b-031b9323fce0', 'authenticated', 'authenticated',
  'seed-wh-07@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Ahmed', 'country', 'United Arab Emirates', 'location', 'Dubai'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), '99a216de-4979-48a1-b31b-031b9323fce0', '99a216de-4979-48a1-b31b-031b9323fce0',
  jsonb_build_object('sub', '99a216de-4979-48a1-b31b-031b9323fce0', 'email', 'seed-wh-07@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Ahmed Hassan' WHERE user_id = '99a216de-4979-48a1-b31b-031b9323fce0';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  '99a216de-4979-48a1-b31b-031b9323fce0', 'Ahmed', 'male', 'female', '1988-06-15',
  'Entrepreneur who''s lived in five cities and finally ready to plant roots. Faith and family matter most to me.', ARRAY['Faith','Family','Travel','Books','Deep talks']::text[], 'United Arab Emirates', 'Dubai',
  ARRAY['/wandering-hearts/avatar-male.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('99a216de-4979-48a1-b31b-031b9323fce0', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '70a6cd4f-727a-4482-800a-7b31df537062', 'authenticated', 'authenticated',
  'seed-wh-08@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Ryan', 'country', 'South Africa', 'location', 'Stellenbosch'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), '70a6cd4f-727a-4482-800a-7b31df537062', '70a6cd4f-727a-4482-800a-7b31df537062',
  jsonb_build_object('sub', '70a6cd4f-727a-4482-800a-7b31df537062', 'email', 'seed-wh-08@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Ryan Fischer' WHERE user_id = '70a6cd4f-727a-4482-800a-7b31df537062';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  '70a6cd4f-727a-4482-800a-7b31df537062', 'Ryan', 'male', 'female', '2001-06-15',
  'Winemaker''s son turned winemaker myself. Give me a vineyard sunset and good company any day.', ARRAY['Nature','Cooking','Music','Hiking','Quiet evenings']::text[], 'South Africa', 'Stellenbosch',
  ARRAY['/wandering-hearts/avatar-male.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('70a6cd4f-727a-4482-800a-7b31df537062', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '4e68bcf3-2ba6-42a6-b786-47ae1510e9e8', 'authenticated', 'authenticated',
  'seed-wh-09@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Michael', 'country', 'Nigeria', 'location', 'Lagos'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), '4e68bcf3-2ba6-42a6-b786-47ae1510e9e8', '4e68bcf3-2ba6-42a6-b786-47ae1510e9e8',
  jsonb_build_object('sub', '4e68bcf3-2ba6-42a6-b786-47ae1510e9e8', 'email', 'seed-wh-09@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Michael Adeyemi' WHERE user_id = '4e68bcf3-2ba6-42a6-b786-47ae1510e9e8';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  '4e68bcf3-2ba6-42a6-b786-47ae1510e9e8', 'Michael', 'male', 'female', '1981-06-15',
  'Doctor, widower, rebuilding a life full of laughter again. My daughters keep me grounded.', ARRAY['Family','Faith','Books','Deep talks','Cooking']::text[], 'Nigeria', 'Lagos',
  ARRAY['/wandering-hearts/avatar-male.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('4e68bcf3-2ba6-42a6-b786-47ae1510e9e8', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '5b7d4bf3-7c04-489a-a608-6f0c37dc5c21', 'authenticated', 'authenticated',
  'seed-wh-10@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Connor', 'country', 'Canada', 'location', 'Toronto'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), '5b7d4bf3-7c04-489a-a608-6f0c37dc5c21', '5b7d4bf3-7c04-489a-a608-6f0c37dc5c21',
  jsonb_build_object('sub', '5b7d4bf3-7c04-489a-a608-6f0c37dc5c21', 'email', 'seed-wh-10@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Connor Bryant' WHERE user_id = '5b7d4bf3-7c04-489a-a608-6f0c37dc5c21';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  '5b7d4bf3-7c04-489a-a608-6f0c37dc5c21', 'Connor', 'male', 'female', '1990-06-15',
  'Teacher who spends summers backpacking. Looking for someone who isn''t afraid of a spontaneous road trip.', ARRAY['Adventure','Travel','Hiking','Music','Nature']::text[], 'Canada', 'Toronto',
  ARRAY['/wandering-hearts/avatar-male.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('5b7d4bf3-7c04-489a-a608-6f0c37dc5c21', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', 'b4dce010-e8a5-4708-bc6c-14bf5a0ee6f2', 'authenticated', 'authenticated',
  'seed-wh-11@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Naledi', 'country', 'South Africa', 'location', 'Johannesburg'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), 'b4dce010-e8a5-4708-bc6c-14bf5a0ee6f2', 'b4dce010-e8a5-4708-bc6c-14bf5a0ee6f2',
  jsonb_build_object('sub', 'b4dce010-e8a5-4708-bc6c-14bf5a0ee6f2', 'email', 'seed-wh-11@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Naledi Mahlangu' WHERE user_id = 'b4dce010-e8a5-4708-bc6c-14bf5a0ee6f2';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  'b4dce010-e8a5-4708-bc6c-14bf5a0ee6f2', 'Naledi', 'female', 'male', '1998-06-15',
  'Marketing manager who bakes on weekends and never misses a sunrise hike. Big believer in showing up for the people you love.', ARRAY['Hiking','Cooking','Family','Music','Nature']::text[], 'South Africa', 'Johannesburg',
  ARRAY['/wandering-hearts/avatar-female.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('b4dce010-e8a5-4708-bc6c-14bf5a0ee6f2', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '9cd297d1-b074-4a95-9372-325029610642', 'authenticated', 'authenticated',
  'seed-wh-12@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Amara', 'country', 'Nigeria', 'location', 'Lagos'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), '9cd297d1-b074-4a95-9372-325029610642', '9cd297d1-b074-4a95-9372-325029610642',
  jsonb_build_object('sub', '9cd297d1-b074-4a95-9372-325029610642', 'email', 'seed-wh-12@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Amara Nwosu' WHERE user_id = '9cd297d1-b074-4a95-9372-325029610642';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  '9cd297d1-b074-4a95-9372-325029610642', 'Amara', 'female', 'male', '1993-06-15',
  'Fashion designer with an eye for detail and a heart for deep conversation over good wine.', ARRAY['Art','Deep talks','Travel','Music','Dancing']::text[], 'Nigeria', 'Lagos',
  ARRAY['/wandering-hearts/avatar-female.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('9cd297d1-b074-4a95-9372-325029610642', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '67ce739c-2dca-4ced-9b7c-e7364d78d198', 'authenticated', 'authenticated',
  'seed-wh-13@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Sarah', 'country', 'United Kingdom', 'location', 'London'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), '67ce739c-2dca-4ced-9b7c-e7364d78d198', '67ce739c-2dca-4ced-9b7c-e7364d78d198',
  jsonb_build_object('sub', '67ce739c-2dca-4ced-9b7c-e7364d78d198', 'email', 'seed-wh-13@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Sarah Bennett' WHERE user_id = '67ce739c-2dca-4ced-9b7c-e7364d78d198';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  '67ce739c-2dca-4ced-9b7c-e7364d78d198', 'Sarah', 'female', 'male', '1987-06-15',
  'Nurse, dog mum, incurable romantic. I find joy in quiet evenings and long walks.', ARRAY['Quiet evenings','Nature','Books','Faith','Family']::text[], 'United Kingdom', 'London',
  ARRAY['/wandering-hearts/avatar-female.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('67ce739c-2dca-4ced-9b7c-e7364d78d198', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', 'a49c7490-c2b4-47a4-a836-00c50e96cff0', 'authenticated', 'authenticated',
  'seed-wh-14@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Zanele', 'country', 'South Africa', 'location', 'Cape Town'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), 'a49c7490-c2b4-47a4-a836-00c50e96cff0', 'a49c7490-c2b4-47a4-a836-00c50e96cff0',
  jsonb_build_object('sub', 'a49c7490-c2b4-47a4-a836-00c50e96cff0', 'email', 'seed-wh-14@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Zanele Khumalo' WHERE user_id = 'a49c7490-c2b4-47a4-a836-00c50e96cff0';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  'a49c7490-c2b4-47a4-a836-00c50e96cff0', 'Zanele', 'female', 'male', '2000-06-15',
  'Graphic designer and coffee snob. Looking for someone to explore the city''s hidden corners with.', ARRAY['Art','Coffee','Adventure','Music','Travel']::text[], 'South Africa', 'Cape Town',
  ARRAY['/wandering-hearts/avatar-female.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('a49c7490-c2b4-47a4-a836-00c50e96cff0', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', 'c9d6fccb-f648-49ee-87fe-d9011fca6079', 'authenticated', 'authenticated',
  'seed-wh-15@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Fatima', 'country', 'United Arab Emirates', 'location', 'Dubai'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), 'c9d6fccb-f648-49ee-87fe-d9011fca6079', 'c9d6fccb-f648-49ee-87fe-d9011fca6079',
  jsonb_build_object('sub', 'c9d6fccb-f648-49ee-87fe-d9011fca6079', 'email', 'seed-wh-15@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Fatima Al-Rashid' WHERE user_id = 'c9d6fccb-f648-49ee-87fe-d9011fca6079';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  'c9d6fccb-f648-49ee-87fe-d9011fca6079', 'Fatima', 'female', 'male', '1982-06-15',
  'Business consultant and mother of one, rediscovering what I want after years of putting everyone else first.', ARRAY['Faith','Family','Travel','Books','Deep talks']::text[], 'United Arab Emirates', 'Dubai',
  ARRAY['/wandering-hearts/avatar-female.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('c9d6fccb-f648-49ee-87fe-d9011fca6079', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '4ef245bf-55ad-4090-9eb3-b1e5875ab7a0', 'authenticated', 'authenticated',
  'seed-wh-16@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Priya', 'country', 'South Africa', 'location', 'Durban'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), '4ef245bf-55ad-4090-9eb3-b1e5875ab7a0', '4ef245bf-55ad-4090-9eb3-b1e5875ab7a0',
  jsonb_build_object('sub', '4ef245bf-55ad-4090-9eb3-b1e5875ab7a0', 'email', 'seed-wh-16@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Priya Naidoo' WHERE user_id = '4ef245bf-55ad-4090-9eb3-b1e5875ab7a0';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  '4ef245bf-55ad-4090-9eb3-b1e5875ab7a0', 'Priya', 'female', 'male', '1996-06-15',
  'Physiotherapist who loves the ocean more than is reasonable. Seeking someone kind, curious, and a little adventurous.', ARRAY['Fitness','Nature','Adventure','Cooking','Music']::text[], 'South Africa', 'Durban',
  ARRAY['/wandering-hearts/avatar-female.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('4ef245bf-55ad-4090-9eb3-b1e5875ab7a0', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', 'b8e68104-d5de-4ce4-8491-d3db5a35c153', 'authenticated', 'authenticated',
  'seed-wh-17@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Emily', 'country', 'Australia', 'location', 'Sydney'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), 'b8e68104-d5de-4ce4-8491-d3db5a35c153', 'b8e68104-d5de-4ce4-8491-d3db5a35c153',
  jsonb_build_object('sub', 'b8e68104-d5de-4ce4-8491-d3db5a35c153', 'email', 'seed-wh-17@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Emily Carter' WHERE user_id = 'b8e68104-d5de-4ce4-8491-d3db5a35c153';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  'b8e68104-d5de-4ce4-8491-d3db5a35c153', 'Emily', 'female', 'male', '1976-06-15',
  'Retired teacher, avid gardener, grandmother of three wonderful grandkids. Looking for genuine companionship.', ARRAY['Nature','Farming','Family','Books','Quiet evenings']::text[], 'Australia', 'Sydney',
  ARRAY['/wandering-hearts/avatar-female.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('b8e68104-d5de-4ce4-8491-d3db5a35c153', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '6f1f8674-acdb-4f25-9335-913a22a62534', 'authenticated', 'authenticated',
  'seed-wh-18@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Thandiwe', 'country', 'South Africa', 'location', 'Pretoria'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), '6f1f8674-acdb-4f25-9335-913a22a62534', '6f1f8674-acdb-4f25-9335-913a22a62534',
  jsonb_build_object('sub', '6f1f8674-acdb-4f25-9335-913a22a62534', 'email', 'seed-wh-18@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Thandiwe Zulu' WHERE user_id = '6f1f8674-acdb-4f25-9335-913a22a62534';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  '6f1f8674-acdb-4f25-9335-913a22a62534', 'Thandiwe', 'female', 'male', '1991-06-15',
  'Accountant with a wild love of dancing and Sunday church. I laugh loudly and love harder.', ARRAY['Dancing','Faith','Family','Music','Deep talks']::text[], 'South Africa', 'Pretoria',
  ARRAY['/wandering-hearts/avatar-female.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('6f1f8674-acdb-4f25-9335-913a22a62534', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', '92bce748-03f7-4f0c-99ef-7459b8c833f4', 'authenticated', 'authenticated',
  'seed-wh-19@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Chiara', 'country', 'Netherlands', 'location', 'Amsterdam'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), '92bce748-03f7-4f0c-99ef-7459b8c833f4', '92bce748-03f7-4f0c-99ef-7459b8c833f4',
  jsonb_build_object('sub', '92bce748-03f7-4f0c-99ef-7459b8c833f4', 'email', 'seed-wh-19@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Chiara Moretti' WHERE user_id = '92bce748-03f7-4f0c-99ef-7459b8c833f4';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  '92bce748-03f7-4f0c-99ef-7459b8c833f4', 'Chiara', 'female', 'male', '1997-06-15',
  'Architect, cyclist, and terrible cook trying to get better. Looking for someone patient and kind.', ARRAY['Travel','Art','Adventure','Cooking','Deep talks']::text[], 'Netherlands', 'Amsterdam',
  ARRAY['/wandering-hearts/avatar-female.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('92bce748-03f7-4f0c-99ef-7459b8c833f4', 'wh-seed test profile');


INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) VALUES (
  '00000000-0000-0000-0000-000000000000', 'd5e7d0df-ebab-4039-b88e-122d0caaf802', 'authenticated', 'authenticated',
  'seed-wh-20@sow2grow.test', crypt(gen_random_uuid()::text, gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('first_name', 'Boitumelo', 'country', 'South Africa', 'location', 'Bloemfontein'),
  false, false, now(), now(), '', '', '', '', '', '', '', ''
);

INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)
VALUES (
  gen_random_uuid(), 'd5e7d0df-ebab-4039-b88e-122d0caaf802', 'd5e7d0df-ebab-4039-b88e-122d0caaf802',
  jsonb_build_object('sub', 'd5e7d0df-ebab-4039-b88e-122d0caaf802', 'email', 'seed-wh-20@sow2grow.test', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
);

UPDATE public.profiles SET display_name = 'Boitumelo Sithole' WHERE user_id = 'd5e7d0df-ebab-4039-b88e-122d0caaf802';

INSERT INTO public.tribal_hearts_profiles (
  user_id, display_first_name, gender, seeking, birthdate, bio, interests,
  location_country, location_region, photos, status, seeking_intent, is_seed
) VALUES (
  'd5e7d0df-ebab-4039-b88e-122d0caaf802', 'Boitumelo', 'female', 'male', '1979-06-15',
  'Farm owner and mother of three grown kids. Looking for a partner to grow old with on the land I love.', ARRAY['Farming','Family','Nature','Faith','Quiet evenings']::text[], 'South Africa', 'Bloemfontein',
  ARRAY['/wandering-hearts/avatar-female.svg']::text[], 'active', 'connection', true
);

INSERT INTO public.s2g_agent_free_access (user_id, note)
VALUES ('d5e7d0df-ebab-4039-b88e-122d0caaf802', 'wh-seed test profile');

COMMIT;
