// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Use to verify the MCP connection is working.",
  inputSchema: {
    text: z.string().min(1).describe("Text to echo back.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-public-orchards.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z2 } from "npm:zod@^4.4.3";
var list_public_orchards_default = defineTool2({
  name: "list_public_orchards",
  title: "List public orchards",
  description: "List public, live orchards on Sow2Grow. Returns handle, title, tagline, and public URL. Use for research or discovery.",
  inputSchema: {
    query: z2.string().optional().describe("Optional case-insensitive search over orchard title/tagline."),
    limit: z2.number().int().optional().describe("Maximum rows to return (default 20, max 50).")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ query, limit }) => {
    const url = process.env.SUPABASE_URL;
    const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !anon) {
      return {
        content: [
          { type: "text", text: "MCP server missing Supabase configuration." }
        ],
        isError: true
      };
    }
    const cap = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = createClient(url, anon, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("orchards").select("handle,title,tagline,status").eq("status", "live").order("created_at", { ascending: false }).limit(cap);
    if (query && query.trim()) {
      const term = `%${query.trim()}%`;
      q = q.or(`title.ilike.${term},tagline.ilike.${term}`);
    }
    const { data, error } = await q;
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    const rows = (data ?? []).map((r) => ({
      handle: r.handle,
      title: r.title,
      tagline: r.tagline ?? null,
      url: r.handle ? `https://sow2growapp.com/orchard/${r.handle}` : null
    }));
    return {
      content: [
        {
          type: "text",
          text: rows.length === 0 ? "No public orchards found." : `Found ${rows.length} orchard(s):
${rows.map(
            (r) => `- ${r.title}${r.handle ? ` (@${r.handle})` : ""}${r.tagline ? ` \u2014 ${r.tagline}` : ""}`
          ).join("\n")}`
        }
      ],
      structuredContent: { orchards: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sow2grow-mcp",
  title: "Sow2Grow MCP",
  version: "0.1.0",
  instructions: "Sow2Grow public tools. Use `echo` to verify connectivity, and `list_public_orchards` to discover live orchards on the Sow2Grow tribal marketplace.",
  tools: [echo_default, list_public_orchards_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
