// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// Use environment variables instead of hardcoded values
// This prevents secrets from being exposed in the codebase
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://zuwkgasbkpjlxzsjzumu.supabase.co";
// Support both VITE_SUPABASE_PUBLISHABLE_KEY and VITE_SUPABASE_ANON_KEY for backward compatibility
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || "sb_publishable_Z8-I1gu2Q1yid1Q4jKRf7Q_jSGcsVpa";

// Validate environment variables (only warn in development, allow fallback values)
if (import.meta.env.DEV && (!import.meta.env.VITE_SUPABASE_URL || (!import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY && !import.meta.env.VITE_SUPABASE_ANON_KEY))) {
  console.warn('⚠️ Using fallback Supabase configuration. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file.');
}

// Reported live, 2026-09-15: a session whose refresh token had gone
// invalid (revoked/expired) left the app in a half-authed limbo instead
// of a clean re-login -- autoRefreshToken keeps retrying in the
// background, but nothing detects a refresh that's actually FAILING, so
// React state kept showing "signed in" (stale session object) while
// every real API call 401'd underneath it. Symptom: buttons whose own
// render depends on a query that 401s (AdminButton's user_roles fetch)
// silently render as if nothing happened.
//
// Wrapping fetch is the one place that sees EVERY request this client
// makes, regardless of which hook/component issued it. A 401 from any
// endpoint OTHER than Supabase's own /auth/v1/* (a bad login attempt or
// a normal token-refresh cycle there is an expected, user-facing
// outcome, not evidence of a stale session elsewhere) means our access
// token is dead and auto-refresh isn't recovering it -- force a clean
// sign-out and send the tab back to /login rather than leaving it
// running on a session that looks alive but silently fails everything.
let forcingReauth = false;
/** True only if a Supabase auth session is actually stored locally --
 * cheap, synchronous, no network call. A 401 with NO stored session at
 * all cannot possibly mean "the session died"; there was never one to
 * begin with (an anonymous visitor on e.g. the login page). */
function hasStoredSession(): boolean {
  try {
    return Object.keys(localStorage).some((k) => k.startsWith('sb-') && k.endsWith('-auth-token'));
  } catch {
    return false; // localStorage unavailable -- can't confirm a session exists, so don't assume one died
  }
}
async function fetchWithAuthGuard(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const res = await fetch(input, init);
  if (res.status === 401 && !forcingReauth) {
    const url = typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
    // Live incident, 2026-09-15: a missing anon EXECUTE grant on an
    // unrelated RPC (check_rate_limit_enhanced) 401'd on every /login
    // page load, before any session ever existed -- this guard treated
    // THAT as "session died," force-signed-out and hard-redirected
    // (window.location.href) mid-keystroke, wiping the login form before
    // submit ever ran. A 401 status alone conflates two very different
    // things: our access token is genuinely dead (this guard's actual
    // job), vs. a plain Postgres permission-denied error (SQLSTATE
    // 42501) that PostgREST also reports as 401 -- the exact case here.
    // Two independent checks before treating it as the former: (1) a
    // session must actually be stored (an anonymous caller has nothing
    // to lose), and (2) the response body must be PostgREST's OWN
    // JWT-related error, not a passthrough Postgres error with its own
    // unrelated SQLSTATE.
    if (!url.includes('/auth/v1/') && hasStoredSession()) {
      let isJwtFailure = false;
      try {
        const body = await res.clone().json();
        const code = typeof body?.code === 'string' ? body.code : '';
        const message = typeof body?.message === 'string' ? body.message : '';
        isJwtFailure = code.startsWith('PGRST') && /jwt|token/i.test(message);
      } catch {
        // Non-JSON/unreadable body -- can't confirm it's really a JWT
        // failure, so don't assume the worst.
      }
      if (isJwtFailure) {
        forcingReauth = true;
        console.warn('[supabase] 401 (expired/invalid JWT) on a non-auth endpoint -- session refresh is failing, forcing a clean re-login', url);
        try { await supabase.auth.signOut(); } catch { /* session may already be dead server-side; clear locally regardless */ }
        try {
          Object.keys(localStorage)
            .filter((k) => k.startsWith('sb-') && k.endsWith('-auth-token'))
            .forEach((k) => localStorage.removeItem(k));
        } catch { /* localStorage unavailable (private mode, quota) -- redirect still recovers the tab */ }
        window.location.href = '/login?session_expired=1';
      }
    }
  }
  return res;
}

// Export the Supabase client instance
// Usage in other files: import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    fetch: fetchWithAuthGuard,
  },
});

// Add session monitoring (production-safe)
supabase.auth.onAuthStateChange((event, session) => {
  // Only log essential auth events in production
  if (process.env.NODE_ENV === 'development') {
    console.log('🔐 SUPABASE AUTH EVENT:', event, {
      hasSession: !!session,
      userId: session?.user?.id,
      accessToken: session?.access_token ? 'present' : 'missing',
      refreshToken: session?.refresh_token ? 'present' : 'missing'
    });
  }
  
  // Enhanced security monitoring for auth events
  if (event === 'SIGNED_IN' && session) {
    // Log successful authentication for security monitoring
    supabase.rpc('log_security_event_enhanced', {
      event_type: 'user_signed_in',
      target_user_id: session.user.id,
      event_details: { timestamp: new Date().toISOString() },
      severity_level: 'info'
    }).then(({ error }) => {
      if (error && process.env.NODE_ENV === 'development') {
        console.warn('Failed to log security event:', error);
      }
    });
  }
  
  if (event === 'SIGNED_OUT') {
    // Log sign out events
    supabase.rpc('log_security_event_enhanced', {
      event_type: 'user_signed_out',
      event_details: { timestamp: new Date().toISOString() },
      severity_level: 'info'
    }).then(({ error }) => {
      if (error && process.env.NODE_ENV === 'development') {
        console.warn('Failed to log security event:', error);
      }
    });
  }
  
  // Database connection validation (production-safe)
  if (event === 'TOKEN_REFRESHED' || event === 'SIGNED_IN') {
    supabase.from('profiles').select('id').limit(1).then(({ error }) => {
      if (error && process.env.NODE_ENV === 'development') {
        console.error('❌ Database connection failed after auth event:', error);
      }
    });
  }
});